name: 'trino_project'
version: '1.0.0'
config-version: 2
profile: 'trino'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
vars:
  mysql_catalog: mysql
  mysql_schema: sample
models:
  trino_project:
      materialized: table
      catalog: postgres